// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tasks.Data;

#nullable disable

namespace Session4.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("tasks.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmed Khaled Tawfik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Naguib Mahfouz"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mustafa Mahmoud"
                        });
                });

            modelBuilder.Entity("tasks.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Isbn = "",
                            PageCount = 150,
                            Title = "Paranormal",
                            Year = 1993
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Isbn = "",
                            PageCount = 192,
                            Title = "Utopia",
                            Year = 2008
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Isbn = "",
                            PageCount = 420,
                            Title = "Palace Walk",
                            Year = 1956
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Isbn = "",
                            PageCount = 460,
                            Title = "Palace of Desire",
                            Year = 1957
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Isbn = "",
                            PageCount = 380,
                            Title = "Sugar Street",
                            Year = 1957
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Isbn = "",
                            PageCount = 180,
                            Title = "Dialogue with an Atheist Friend",
                            Year = 1974
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            Isbn = "",
                            PageCount = 520,
                            Title = "My Journey from Doubt to Belief",
                            Year = 1970
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Isbn = "",
                            PageCount = 210,
                            Title = "The Spider",
                            Year = 1965
                        });
                });

            modelBuilder.Entity("tasks.Entities.BookTag", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 1,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 3,
                            TagId = 2
                        },
                        new
                        {
                            BookId = 6,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 7,
                            TagId = 3
                        });
                });

            modelBuilder.Entity("tasks.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Novel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fiction"
                        });
                });

            modelBuilder.Entity("tasks.Entities.Book", b =>
                {
                    b.HasOne("tasks.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("tasks.Entities.BookTag", b =>
                {
                    b.HasOne("tasks.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tasks.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tasks.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
